language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
    # - name: "Python 3.7.1 on Xenial Linux"
    #   python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      addons:
        homebrew:
          packages:
            - bison
            - flex
          update: false # makes things faster
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install mingw python winflexbison3
        - python -m pip install --upgrade pip wheel
        - python -m pip install wheel
        - openssl aes-256-cbc -K $encrypted_721b3232adb3_key -iv $encrypted_721b3232adb3_iv -in secret-files.tar.enc -out secret-files.tar -d
        - tar xvf secret-files.tar
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

after_success:
- ls dist/*
- ls -la
- pip3 install twine
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo chown -R $(whoami):$(whoami) dist;
      python setup.py sdist
  fi
- twine upload --config-file .pypirc-bot dist/*

before_install:
- openssl aes-256-cbc -K $encrypted_721b3232adb3_key -iv $encrypted_721b3232adb3_iv -in secret-files.tar.enc -out secret-files.tar -d
- tar xvf secret-files.tar

install:
- alias python=python3;
- python --version;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull $DOCKER_IMAGE;
  else
      pip3 install --upgrade pip;
      pip3 install -r requirements.txt;
  fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE sh /io/.travis/build-wheels.sh;
   else
      python setup.py bdist_wheel;
   fi
